//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKRTalalaev.DataFolder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }

        private static DBEntities context;

        public static DBEntities GetContext()
        {
            
            if (context == null)
            {
                context = new DBEntities();
            }
            return context;
        }

        public static void ResetContext()
        {
            context = null;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adress> Adress { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Counterparty> Counterparty { get; set; }
        public virtual DbSet<Employer> Employer { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<Operation> Operation { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Street> Street { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<TypeOfOperation> TypeOfOperation { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
