//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKRTalalaev.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public int IdOperation { get; set; }
        public int IdTypeOfOperation { get; set; }
        public string NameOperation { get; set; }
        public System.DateTime DateOperation { get; set; }
        public int IdCounterParty { get; set; }
        public int IdStatus { get; set; }
        public int IdProject { get; set; }
        public int IdType { get; set; }
        public int IdGoods { get; set; }
    
        public virtual Counterparty Counterparty { get; set; }
        public virtual Goods Goods { get; set; }
        public virtual Project Project { get; set; }
        public virtual Status Status { get; set; }
        public virtual TypeOfOperation TypeOfOperation { get; set; }
    }
}
